### ISSUE TITLE
Suggestion: Home-manager support

### ISSUE THREAD

**Issue by dch82** [vlinkz/nix-software-center#43]
It would be nice to be able to configure `home.nix` with this app to install applications not unlike `configuration.nix`.

**Comment by pinkcreeper100** [comment]
something else that is probably ***way*** out of scope is being able to edit snowfall-lib configurations hosted via git

**Comment by dch82** [comment]
Closed due to inactivity

**Comment by pinkcreeper100** [comment]
would probably only be able to implement when https://github.com/snowfallorg/lib gets home-manager support

**Comment by jakehamilton** [comment]
I spoke (briefly) with @vlinkz a few months ago about Home-Manager integration in Snowfall Lib. I think both projects have slowed due to life events, but this should be possible in the near future.

https://github.com/snowfallorg/lib/issues/7

I've been needing to do another pass of my in-progress Home-Manager support and get it pushed up to a branch. Right now I have it functioning on macOS, but need to test on NixOS as well.
